[package]
name = "watchbind"
version = "0.1.17"
authors = ["Fritz Rehde <fritzrehde.work@gmail.com>"]
edition = "2021"
license-file = "LICENSE.md"
documentation = "https://github.com/fritzrehde/watchbind"
homepage = "https://github.com/fritzrehde/watchbind"
repository = "https://github.com/fritzrehde/watchbind"
description = "A cli menu for periodically watching a program's output and executing commands on its lines through keybindings"

[dependencies]
clap = { version = "4.3.0", default-features = false, features = ["std", "help", "cargo", "derive", "error-context"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
toml = { version = "0.7.4", default-features = false, features = ["parse"] }
ratatui = "0.20.1"
crossterm = { version = "0.26", default-features = false }
itertools = "0.10.5"
anyhow = "1.0.71"
indoc = "2.0.1"
derive_more = { version = "0.99.17", default-features = false, features = ["from", "into_iterator"] }
tabwriter = "1.2.1"
strum = "0.24.1"
strum_macros = "0.24.3"
parse-display = "0.8.2"
derive-new = "0.5.9"

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
