[package]
name = "watchbind"
version = "0.1.17"
authors = ["Fritz Rehde <fritzrehde.work@gmail.com>"]
edition = "2021"
license-file = "LICENSE.md"
documentation = "https://github.com/fritzrehde/watchbind"
homepage = "https://github.com/fritzrehde/watchbind"
repository = "https://github.com/fritzrehde/watchbind"
description = "A cli menu for periodically watching a program's output and executing commands on its lines through keybindings"

[dependencies]
clap = { version = "4.3.22", default-features = false, features = ["std", "help", "cargo", "derive", "error-context"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
toml = { version = "0.7.6", default-features = false, features = ["parse"] }
ratatui = "0.22.0"
crossterm = { version = "0.27", default-features = false, features = ["events", "event-stream"] }
itertools = "0.11.0"
anyhow = "1.0.75"
indoc = "2.0.3"
derive_more = { version = "0.99.17", default-features = false, features = ["from", "into_iterator", "as_ref"] }
tabwriter = "1.2.1"
parse-display = "0.8.2"
derive-new = "0.5.9"
simplelog = "0.12.1"
log = "0.4.20"
ranges = "0.3.3"
# TODO: maybe we don't need all tokio and futures features, try to reduce
tokio = { version = "1.32.0", features = ["full"] }
futures = "0.3.28"

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
