[package]
name = "watchbind"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"
description = "A cli menu for periodically watching a program's output and executing commands on its lines through keybindings"

[dependencies]
clap = { version = "3.2.5", default-features = false, features = ["std", "cargo"] }
tui = "0.18"
crossterm = "0.23"
itertools = "0.10.3"
