watched-command = "ls"
interval = 3.0

# cursor line
cursor-bg = "blue"
cursor-boldness = "bold"

# header lines
header-lines = 1
header-fg = "blue"
header-boldness = "non-bold"

# selected lines
selected-bg = "red"

[keybindings]
"esc" = [ "unselect-all", "help-hide" ]
"q" = { operations = "exit", description = "Exit watchbind." }
"j" = "cursor down 1"
"A" = { operations = "select-all", description = "Select all lines." }
"down" = { operations = [ "cursor down 1", "cursor down 1", "cursor down 1" ], description = "Move the cursor down 3 lines in 3 separate steps." }
"J" = { operations = "cursor down 3", description = "Move the cursor down 3 lines in one step." }
"K" = [ 
  "cursor up 1",
  "cursor up 1",
  "cursor up 1"
]
"k" = [ "cursor up 1" ]
"l" = [ "exec -- notify-send \"Printing $lines\"", "reload", "exec -- sleep 1", "unselect-all" ]
"s" = [ "exec -- sleep 3" ]
"S" = [ "exec & -- sleep 3; notify-send \"Hello world\"" ]
"p" = [
  "exec -- notify-send \"Executing echo\"",
  "exec -- echo \"Trying to overwrite watchbind's lines with stdout\"",
  "exec -- echo \"Trying to overwrite watchbind's lines with stderr\" >&2"
]
"e" = [ "exec tui -- $EDITOR \"$line\"" ]
