command = "date"
interval = 1.0
fg = "none"
bg = "none"
fg_plus = "black"
bg_plus = "blue"
bold = false
bold_plus = true

[keybindings]
"l" = "dunstify \"Printing $LINE\""
"x" = "dunstify \"Deleted $LINE\""
