"command" = "ls -la"
"interval" = 3.0
"fg+" = "black"
"bg+" = "blue"
"bold" = false
"bold+" = true
"bg-" = "red"
field-separator = ","

[keybindings]
"q" = [ "exit" ]
"j" = [ "down" ]
"A" = [ "select-all" ]
"down" = [ "down", "down", "down" ]
"J" = [ "down 3" ]
"K" = [ 
  "up",
  "up",
  "up"
]
"k" = [ "up" ]
"l" = [ "dunstify \"Printing $LINES\"", "reload", "unselect-all"]
"s" = [ "sleep 3" ]
"S" = [ "sleep 3 &" ]
