command = "ls"
interval = 5.0
fg = "none"
bg = "none"
fg_plus = "black"
bg_plus = "blue"
bold = true
bold_plus = true

[keybindings]
"l" = "echo \"$LINE\" | '{ print $1 }'"
"x" = "dunstify \"$LINE\""
