command = "ls -la"
interval = 1.0
fg_plus = "black"
bg_plus = "blue"
bold = false
bold_plus = true

[keybindings]
"q" = [ "exit" ]
"j" = [ "next" ]
"J" = [ "next", "next", "next" ]
"K" = [ 
  "previous",
  "previous",
  "previous"
]
"k" = [ "previous" ]
"l" = [ "dunstify \"Printing $LINE\"" ]
"s" = [ "sleep 3" ]
"S" = [ "sleep 3 &" ]
