command = "ls -la"
interval = 1.0
fg_plus = "black"
bg_plus = "blue"
bold = false
bold_plus = true

[keybindings]
"q" = [ "exit" ]
"j" = [ "down" ]
"down" = [ "down", "down", "down" ]
"J" = [ "down 3" ]
"K" = [ 
  "up",
  "up",
  "up"
]
"k" = [ "up" ]
"l" = [ "dunstify \"Printing $LINES\"" ]
"s" = [ "sleep 3" ]
"S" = [ "sleep 3 &" ]
