command = "ls -la"
interval = 1.0
fg = "none"
bg = "none"
fg_plus = "black"
bg_plus = "blue"
bold = false
bold_plus = true

[keybindings]
"q" = "exit"
"j" = "next"
"k" = "previous"
"l" = "dunstify \"Printing $LINE\""
"x" = "kitty &"
"s" = "sleep 3"
"S" = "sleep 3 &"
